/* SPDX-License-Identifier: GPL-3.0-only */
/* SPDX-FileCopyrightText: 2025-2026 Qodeca sp. z o.o. */
/* GENERATED by scripts/design-sync.mjs from design/claims.json — do not edit.
   Every value below was derived from src/ at build time. design/claims.test.ts
   re-derives them on every CI run and fails naming the card that drifted. */
window.ERFANA_CLAIMS = {
  "spinner-keyframes": {
    "value": 6,
    "label": "spin keyframes in the renderer",
    "card": "system/foundations/motion.html"
  },
  "spinner-durations": {
    "value": 3,
    "label": "distinct durations those spinners run at",
    "card": "system/foundations/motion.html"
  },
  "icon-registry-bypass": {
    "value": 50,
    "label": "files importing the icon library directly instead of the registry",
    "card": "system/components/icon/index.html"
  },
  "prefers-color-scheme-blocks": {
    "value": 0,
    "label": "prefers-color-scheme blocks shipping in the renderer",
    "card": "system/foundations/colors.html"
  },
  "aria-invalid-uses": {
    "value": 0,
    "label": "places the renderer marks a field invalid to assistive tech",
    "card": "system/components/form/index.html"
  },
  "zindex-css-literals": {
    "value": 2,
    "label": "stylesheets setting a bare z-index instead of a token",
    "card": "system/foundations/layering.html"
  },
  "zindex-js-literals": {
    "value": 8,
    "label": "renderer files mirroring a z-index into TypeScript",
    "card": "system/foundations/layering.html"
  },
  "colour-tokens": {
    "value": 108,
    "label": "colour tokens declared in design-tokens.css",
    "card": "system/foundations/colors.html"
  },
  "reduced-motion-gaps": {
    "value": 12,
    "label": "stylesheets that animate without a reduced-motion escape",
    "card": "system/foundations/motion.html"
  },
  "contrast-secondary-on-panel": {
    "value": 3.72,
    "label": "--color-text-secondary on --color-bg-secondary",
    "card": "system/foundations/colors.html"
  },
  "contrast-tertiary-on-panel": {
    "value": 6.33,
    "label": "--color-text-tertiary on --color-bg-secondary",
    "card": "system/components/permission-band/index.html"
  },
  "contrast-input-border": {
    "value": 3.11,
    "label": "--color-border-input against --color-bg-secondary",
    "card": "system/components/form/index.html"
  },
  "contrast-placeholder": {
    "value": 4.53,
    "label": "--color-text-placeholder on --color-bg-input",
    "card": "system/components/form/index.html"
  },
  "warning-tokens": {
    "value": 5,
    "label": "tokens declared for the meaning \"warning\"",
    "card": "system/components/feedback/index.html"
  },
  "error-tokens": {
    "value": 7,
    "label": "tokens declared for the meaning \"error\"",
    "card": "system/components/feedback/index.html"
  },
  "alert-role-files": {
    "value": 11,
    "label": "files announcing with role=\"alert\"",
    "card": "system/components/feedback/index.html"
  },
  "context-menu-dependants": {
    "value": 14,
    "label": "files that import a context menu component",
    "card": "system/components/menu/index.html"
  },
  "outline-none-unreplaced": {
    "value": 8,
    "label": "stylesheets that remove an outline with no :focus-visible rule in the same file",
    "card": "system/foundations/focus.html"
  },
  "contrast-focus-ring": {
    "value": 6.24,
    "label": "--color-border-focus against --color-bg-secondary",
    "card": "system/foundations/focus.html"
  },
  "contrast-warning-on-panel": {
    "value": 5.95,
    "label": "--color-warning on --color-bg-secondary",
    "card": "system/components/permission-band/index.html"
  }
};

(function fillClaims() {
  var fill = function () {
    var spans = document.querySelectorAll('[data-claim]');
    for (var i = 0; i < spans.length; i += 1) {
      var id = spans[i].getAttribute('data-claim');
      var claim = window.ERFANA_CLAIMS[id];
      if (!claim) {
        /* Loud on purpose. A card asking for a number that no longer exists
           must not render an empty gap that reads as a typo. */
        spans[i].textContent = '[no claim "' + id + '"]';
        spans[i].style.color = 'var(--color-error)';
        continue;
      }
      spans[i].textContent = String(claim.value);
      spans[i].title = claim.label;
    }
  };
  if (document.readyState === 'loading') document.addEventListener('DOMContentLoaded', fill);
  else fill();
})();
